[package]
name = "arctime"
version = "0.1.0"
authors = ["Klas Segeljakt <klasseg@kth.se>"]
edition = "2018"

[dependencies]
kompact = { git = "https://github.com/kompics/kompact" }
paste = "1.0.5"
slog = "2.7.0"
